version: "3"

services:

  deploy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app

  util:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    entrypoint: [ "bash" ]
